# -*- coding: utf-8 -*-
"""Pycaret.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRO0dLK_-30sHS6L8yV2lRrnTwYAXV7d
"""

!pip install pycaret

!pip install scikit-learn==1.0.2
!pip install imbalanced-learn==0.8.1

import pandas as pd
from pycaret.classification import *

data = pd.read_csv('/content/drive/MyDrive/CSV/ANALISIS BD/healthcare-dataset-stroke-data.csv')

# Manejar valores faltantes (si aplica)
data = data.fillna(method='ffill')

# Configurar el entorno
clf1 = setup(
    data=data,
    target='stroke',
    session_id=123,
    fix_imbalance=True,

)

# Comparar modelos
best_model = compare_models()

# Mostrar detalles del mejor modelo
print(best_model)

# Entrenar el mejor modelo
final_model = finalize_model(best_model)

# Guardar el modelo entrenado
#save_model(final_model, 'best_stroke_model')

